version: '3'
services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - /Volumes/Data/AI/MyNLP/RAG/data/database_data/qdrant:/qdrant/storage

  postgres:
    image: postgres:15.5
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mybot
    ports:
      - 5432:5432
    volumes:
      - /Volumes/Data/AI/MyNLP/RAG/data/database_data/postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - /Volumes/Data/AI/MyNLP/RAG/data/database_data/rabbitmq/data/:/var/lib/rabbitmq/
        - /Volumes/Data/AI/MyNLP/RAG/data/database_data/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge

configs:
  qdrant_config:
    content: |
      log_level: INFO
